changelog:
  categories:
    - title: New Features
      labels:
        - feature
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
        - fix
        - bugfix
    - title: Other Changes
      labels:
        - '*'
  exclude:
    labels:
      - dependencies
      - automation
