---
services:
  lab-dash-frontend:
      container_name: lab-dash-frontend
      image: ghcr.io/anthonygress/lab-dash-frontend:latest
      ports:
          - 2022:80
      restart: unless-stopped
  lab-dash-backend:
      container_name: lab-dash-backend
      image: ghcr.io/anthonygress/lab-dash-backend:latest
      restart: unless-stopped
