---
services:
  lab-dash:
      container_name: lab-dash
      image: ghcr.io/anthonygress/lab-dash:latest
      ports:
        - 2022:2022
      # volumes:
        # - /docker/lab-dash/config:/config
      restart: unless-stopped
