---
services:
  lab-dash-frontend:
      build: ./frontend
      container_name: lab-dash-frontend
      image: ghcr.io/anthonygress/lab-dash-frontend:latest
      environment:
        - VITE_API_URL=http://lab-dash-backend:5000
      ports:
        - 2022:80
      extra_hosts:
        - "host.docker.internal:host-gateway"
      restart: unless-stopped
  lab-dash-backend:
      build: ./backend
      container_name: lab-dash-backend
      image: ghcr.io/anthonygress/lab-dash-backend:latest
      ports:
        - 5000:5000
      restart: unless-stopped
