---
services:
  lab-dash-frontend:
      container_name: lab-dash-frontend
      image: ghcr.io/anthonygress/lab-dash-frontend:latest
      networks:
        - app_network
      ports:
        - 2022:80
      extra_hosts:
        - "host.docker.internal:host-gateway"
      restart: unless-stopped
  lab-dash-backend:
      container_name: lab-dash-backend
      image: ghcr.io/anthonygress/lab-dash-backend:latest
      networks:
        - app_network
      ports:
        - 5000:5000
      restart: unless-stopped
networks:
  app_network:
    driver: bridge
