{{- if .Values.volumes.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lab-dash.fullname" . }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    app: {{ include "lab-dash.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.config.size }}
{{- end }}

---

{{- if .Values.volumes.uploads.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-dash-uploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.uploads.size }}
{{- end }}