apiVersion: v1
kind: Service
metadata:
  name: {{ include "lab-dash.fullname" . }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    app: {{ include "lab-dash.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2022
      protocol: TCP
      name: http
  selector:
    app: {{ include "lab-dash.name" . }}