name: deploy

on:
  push:
    branches: [ main ]

jobs:
  publish:
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for release notes

      - name: Install Node and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        run: npm install

      - name: Build & Push Docker Image
        run: |
          npm run docker:build
          npm run docker:push

      - run: git fetch --all --tags

      - name: Version Check
        uses: thebongy/version-check@v2
        with:
          file: package.json
          tagFormat: v${version}
          failBuild: false
        id: version_check

      - name: Create Release
        if: steps.version_check.outputs.versionChanged == 'true'
        run: |
          # Get the previous version tag or initial commit
          PREV_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo $(git rev-list --max-parents=0 HEAD))
          CURR_TAG="v${{ steps.version_check.outputs.rawVersion }}"

          # Generate simple release notes with commit messages
          NOTES=$(git log --pretty=format:"* %s" $PREV_TAG..HEAD --no-merges)
          echo "## What's Changed" > release_notes.md
          echo "" >> release_notes.md
          echo "$NOTES" >> release_notes.md

          # Create the release with notes
          gh release create "$CURR_TAG" --notes-file release_notes.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


