name: deploy

on:
  push:
    branches: [ main ]

jobs:
  publish:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Install Node and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        run: npm install

      - name: Build & Push Frontend
        run: |
          cd frontend && npm run docker:build
          npm run docker:push

      - name: Build & Push Backend
        run: |
          cd backend && npm run docker:build
          npm run docker:push



